name: 'my first container action'
description: 'For testing purpose'
author: 'Devendra Sharma'
inputs:
  myInputs:
    description: 'greeting to use'
    required: true
    default: 'Be awesome'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
