on: [push]

jobs:
  my-job:
    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: hello
        uses: ./
        with: 
          myInput: 'Devendra Sharma'
      - name: output
        run: |
          echo ${{ steps.hello.outputs.memory }}
          echo "total memory successfully output"
